version: "3.4"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "3"
      max-size: "100m"

services:
  vouch1:
    image: attestant/vouch:${VOUCH_DOCKER_TAG}
    hostname: vouch1-${MEV_HOST}
    restart: unless-stopped
    command: ["--base-dir=/config"]
    volumes:
      - ./config/vouch1.yml:/config/vouch.yml:ro
      - ./config/vouch-ee.json:/config/vouch-ee.json:ro
      - ./config/certs:/config/certs:ro
    ports:
      - 12345:12345/tcp
    networks:
      - internet_access
    <<: *logging

  vouch2:
    image: attestant/vouch:${VOUCH_DOCKER_TAG}
    hostname: vouch2-${MEV_HOST}
    restart: unless-stopped
    command: ["--base-dir=/config"]
    volumes:
      - ./config/vouch2.yml:/config/vouch.yml:ro
      - ./config/vouch-ee.json:/config/vouch-ee.json:ro
      - ./config/certs:/config/certs:ro
    ports:
      - 12346:12345/tcp
    networks:
      - internet_access
    <<: *logging